# Form implementation generated from reading ui file 'login_window.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Login_Window(object):
    def setupUi(self, Login_Window):
        Login_Window.setObjectName("Login_Window")
        Login_Window.resize(1512, 854)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(Login_Window.sizePolicy().hasHeightForWidth())
        Login_Window.setSizePolicy(sizePolicy)
        Login_Window.setBaseSize(QtCore.QSize(1024, 720))
        Login_Window.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(parent=Login_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(230, 340, 511, 301))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(-1, -1, -1, 10)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.inpt_username = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.inpt_username.setObjectName("inpt_username")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.inpt_username)
        self.label = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.inpt_password = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.inpt_password.setObjectName("inpt_password")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.inpt_password)
        self.verticalLayout.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.btn_giris_yap = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.btn_giris_yap.setObjectName("btn_giris_yap")
        self.verticalLayout.addWidget(self.btn_giris_yap)
        self.btn_kayit_ol = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.btn_kayit_ol.setObjectName("btn_kayit_ol")
        self.verticalLayout.addWidget(self.btn_kayit_ol)
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(300, 210, 411, 111))
        font = QtGui.QFont()
        font.setPointSize(60)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        Login_Window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=Login_Window)
        self.statusbar.setObjectName("statusbar")
        Login_Window.setStatusBar(self.statusbar)

        self.retranslateUi(Login_Window)
        QtCore.QMetaObject.connectSlotsByName(Login_Window)

    def retranslateUi(self, Login_Window):
        _translate = QtCore.QCoreApplication.translate
        Login_Window.setWindowTitle(_translate("Login_Window", "Giriş Ekranı"))
        self.label_2.setText(_translate("Login_Window", "Username"))
        self.label.setText(_translate("Login_Window", "Password"))
        self.btn_giris_yap.setText(_translate("Login_Window", "Giriş Yap"))
        self.btn_kayit_ol.setText(_translate("Login_Window", "Kayıt Ol"))
        self.label_3.setText(_translate("Login_Window", "GİRİŞ EKRANI"))

def MesajYaz():
    print("Merhaba")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login_Window = QtWidgets.QMainWindow()
    ui = Ui_Login_Window()
    ui.setupUi(Login_Window)
    Login_Window.show()
    sys.exit(app.exec())
